DROP TABLE IF EXISTS rfx.bid_items CASCADE;
DROP TABLE IF EXISTS rfx.bids CASCADE;
DROP TABLE IF EXISTS rfx.freight_requests CASCADE;
DROP TABLE IF EXISTS rfx.rfx_responses CASCADE;
DROP TABLE IF EXISTS rfx.rfx_participants CASCADE;
DROP TABLE IF EXISTS rfx.rfx_lanes CASCADE;
DROP TABLE IF EXISTS rfx.rfx_lots CASCADE;
DROP TABLE IF EXISTS rfx.rfx_events CASCADE;
