DELETE FROM core.roles
WHERE tenant_id IS NULL
  AND code IN (
    'PLATFORM_ADMIN',
    'SHIPPER_ADMIN',
    'SHIPPER_LOGIST',
    'CARRIER_ADMIN',
    'CARRIER_DISPATCHER',
    'DRIVER',
    'CONSIGNEE_OPERATOR',
    'PROCUREMENT_MANAGER',
    'FINANCE_MANAGER',
    'GOV_INSPECTOR'
  );
