import type { ControlTowerEvent, ControlTowerShipment } from '~/types/controlTower'

export const CONTROL_TOWER_DEMO_SHIPMENTS: ControlTowerShipment[] = [
  {
    id: 'demo-sh-001',
    shipmentNumber: 'DEMO-SH-001',
    transportOrderId: 'demo-to-001',
    transportOrderNumber: 'DEMO-TO-001',
    shipperName: 'DEMO Shipper LLC',
    carrierName: 'DEMO Carrier LLC',
    route: 'Moscow → Saint Petersburg',
    plannedPickupAt: '2026-08-01T08:00:00Z',
    plannedDeliveryAt: '2026-08-02T18:00:00Z',
    status: 'IN_TRANSIT',
    slaStatus: 'ON_TIME',
    lastEvent: 'IN_TRANSIT',
    lastUpdatedAt: '2026-07-31T10:00:00Z',
  },
  {
    id: 'demo-sh-002',
    shipmentNumber: 'DEMO-SH-002',
    transportOrderId: 'demo-to-002',
    transportOrderNumber: 'DEMO-TO-002',
    shipperName: 'DEMO Shipper LLC',
    carrierName: 'DEMO Carrier LLC',
    route: 'Kazan → Yekaterinburg',
    plannedPickupAt: '2026-07-30T06:00:00Z',
    plannedDeliveryAt: '2026-07-31T20:00:00Z',
    status: 'IN_PICKUP',
    slaStatus: 'AT_RISK',
    lastEvent: 'IN_PICKUP',
    lastUpdatedAt: '2026-07-31T09:30:00Z',
  },
  {
    id: 'demo-sh-003',
    shipmentNumber: 'DEMO-SH-003',
    transportOrderId: 'demo-to-003',
    transportOrderNumber: 'DEMO-TO-003',
    shipperName: 'DEMO Shipper LLC',
    carrierName: 'DEMO Carrier LLC',
    route: 'Novosibirsk → Omsk',
    plannedPickupAt: '2026-07-29T10:00:00Z',
    plannedDeliveryAt: '2026-07-30T22:00:00Z',
    status: 'DELIVERED',
    slaStatus: 'DELAYED',
    lastEvent: 'DELIVERED',
    lastUpdatedAt: '2026-07-31T08:00:00Z',
  },
  {
    id: 'demo-sh-004',
    shipmentNumber: 'DEMO-SH-004',
    transportOrderNumber: 'DEMO-TO-004',
    shipperName: 'DEMO Shipper LLC',
    carrierName: 'DEMO Carrier LLC',
    route: 'Samara → Ufa',
    plannedPickupAt: '2026-08-02T12:00:00Z',
    plannedDeliveryAt: '2026-08-03T12:00:00Z',
    status: 'READY_FOR_BILLING',
    slaStatus: 'ON_TIME',
    lastEvent: 'READY_FOR_BILLING',
    lastUpdatedAt: '2026-07-31T11:00:00Z',
  },
]

export const CONTROL_TOWER_DEMO_EVENTS: ControlTowerEvent[] = [
  {
    id: 'demo-ev-001',
    shipmentId: 'demo-sh-002',
    shipmentNumber: 'DEMO-SH-002',
    type: 'PICKUP_DELAY',
    severity: 'WARNING',
    occurredAt: '2026-07-30T06:00:00Z',
    descriptionKey: 'controlTower.events.descriptions.pickupDelay',
  },
  {
    id: 'demo-ev-002',
    shipmentId: 'demo-sh-003',
    shipmentNumber: 'DEMO-SH-003',
    type: 'MISSING_DOCUMENTS',
    severity: 'WARNING',
    occurredAt: '2026-07-31T08:00:00Z',
    descriptionKey: 'controlTower.events.descriptions.missingDocuments',
  },
]
